name: CI Dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - '.github/**'

jobs:
# test:
#   ...
  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Debug
        run: |
          env | grep GITHUB
          test -r build-info.json && {
            git_hash=$(git rev-parse --short "$GITHUB_SHA")
            git_branch=${GITHUB_REF#refs/heads/}
            git_tag=${{ github.event.release.tag_name }}
            sed "s/REPLACE_WITH_COMMIT/${git_hash}/g;s/REPLACE_WITH_BRANCH/${git_branch}/g" < build-info.json
            # cat build-info.json | jq
          }
        shell: bash
        env:
          ANSIBLE_FORCE_COLOR: "True"
          ANSIBLE_INVENTORY: inventories/testnet/,inventories/ci_user.yml

      - name: Testnet deploying
        run: .github/dispatch_workflow.py
        env:
          APP_ID: "${{ secrets.APP_ID }}"
          APP_PRIVATE_KEY: "${{ secrets.APP_PRIVATE_KEY }}"
          TARGET_REPO: "lidofinance/infra-mainnet"
          TARGET_WORKFLOW: "deploy_testnet_aragon_apps.yaml"
